-- FE에 정의된 "skillData"의 이름을 미리 DB에 저장
INSERT INTO skill (skill_id, name)
VALUES (1, 'JavaScript'),
       (2, 'C'),
       (3, 'Java'),
       (4, 'C++'),
       (5, 'Flutter'),
       (6, 'React'),
       (7,'Python'),
       (8,'C#'),
       (9,'TypeScript'),
       (10,'Kotlin'),
       (11,'Swift'),
       (12,'Node'),
       (13,'Spring'),
       (14,'MySQL'),
       (15,'R'),
       (16,'Oracle'),
       (17,'Dart'),
       (18,'Unity');